export type Product = {
  id: string
  name: string
  brand: string
  category: string
  subcategory?: string
  price: number
  originalPrice?: number
  discount?: number
  rating: number
  reviewCount: number
  image: string
  images: string[]
  badge?: "New" | "Hot" | "Sale" | "Limited" | "Trending"
  inStock: boolean
  emi?: string
  delivery?: string
  warranty: string
  description: string
  highlights: string[]
  specs: { label: string; value: string }[]
  colors?: string[]
  storage?: string[]
  tags?: string[]
}

export type Category = {
  id: string
  name: string
  icon: string
  image: string
  count: number
  description: string
}

export type Brand = {
  id: string
  name: string
  logo: string
  tagline: string
  count: number
}

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "iPhone 16 Pro Max",
    brand: "Apple",
    category: "Smartphones",
    price: 134900,
    originalPrice: 149900,
    discount: 10,
    rating: 4.8,
    reviewCount: 12840,
    image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=900&q=85",
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=900&q=85",
    ],
    badge: "Hot",
    inStock: true,
    emi: "₹4,497/mo",
    delivery: "Free delivery by Tomorrow",
    warranty: "1 Year Apple Warranty",
    description: "The most powerful iPhone ever. A17 Pro chip with a 48MP ProRAW camera system, titanium design, and Action button.",
    highlights: ["A17 Pro chip with 6-core GPU", "48MP main camera with ProRAW", "Titanium body, aerospace-grade", "Action button with customisable shortcuts", "USB-C with Thunderbolt 3 speeds"],
    specs: [
      { label: "Display", value: "6.7-inch Super Retina XDR, ProMotion 120Hz" },
      { label: "Processor", value: "Apple A17 Pro (3nm)" },
      { label: "RAM", value: "8GB" },
      { label: "Camera", value: "48MP + 12MP + 12MP triple" },
      { label: "Battery", value: "4422 mAh" },
      { label: "OS", value: "iOS 18" },
    ],
    colors: ["#1a1a1a", "#f0f0f0", "#8B7355", "#4a6741"],
    storage: ["256GB", "512GB", "1TB"],
    tags: ["bestseller", "5g", "pro"],
  },
  {
    id: "p2",
    name: "Samsung Galaxy S25 Ultra",
    brand: "Samsung",
    category: "Smartphones",
    price: 124999,
    originalPrice: 139999,
    discount: 11,
    rating: 4.7,
    reviewCount: 8420,
    image: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=900&q=85",
    ],
    badge: "New",
    inStock: true,
    emi: "₹4,167/mo",
    delivery: "Free delivery by Tomorrow",
    warranty: "1 Year Samsung Warranty",
    description: "Galaxy AI meets the most capable S Pen yet. Snapdragon 8 Elite with a 200MP camera and all-new titanium frame.",
    highlights: ["Snapdragon 8 Elite processor", "200MP quad camera with AI", "Built-in S Pen", "45W super-fast charging", "7 years OS updates guaranteed"],
    specs: [
      { label: "Display", value: "6.9-inch QHD+ Dynamic AMOLED 2X, 120Hz" },
      { label: "Processor", value: "Snapdragon 8 Elite" },
      { label: "RAM", value: "12GB" },
      { label: "Camera", value: "200MP + 50MP + 10MP + 12MP" },
      { label: "Battery", value: "5000 mAh" },
      { label: "OS", value: "Android 15, One UI 7" },
    ],
    colors: ["#1a1a2e", "#f5f5f5", "#2d5a27", "#8b4513"],
    storage: ["256GB", "512GB", "1TB"],
    tags: ["5g", "s-pen", "ai"],
  },
  {
    id: "p3",
    name: "MacBook Pro 14\" M4 Pro",
    brand: "Apple",
    category: "Laptops",
    price: 199900,
    originalPrice: 219900,
    discount: 9,
    rating: 4.9,
    reviewCount: 5632,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=900&q=85",
      "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=900&q=85",
    ],
    badge: "Hot",
    inStock: true,
    emi: "₹6,663/mo",
    delivery: "Free delivery in 2 days",
    warranty: "1 Year Apple Warranty",
    description: "Supercharged by M4 Pro chip. Up to 24 core CPU, 40 core GPU, up to 64GB unified memory — in a thin fanless design.",
    highlights: ["M4 Pro chip — 14-core CPU", "Liquid Retina XDR display, 3024×1964", "Up to 22 hours battery", "MagSafe 3 charging", "3× Thunderbolt 5 ports"],
    specs: [
      { label: "Display", value: "14.2-inch Liquid Retina XDR, 120Hz ProMotion" },
      { label: "Processor", value: "Apple M4 Pro (14-core)" },
      { label: "RAM", value: "24GB Unified Memory" },
      { label: "Storage", value: "512GB SSD" },
      { label: "Battery", value: "Up to 22 hours" },
      { label: "Weight", value: "1.61 kg" },
    ],
    colors: ["#c0c0c0", "#1a1a1a"],
    storage: ["512GB", "1TB", "2TB"],
    tags: ["bestseller", "m4", "professional"],
  },
  {
    id: "p4",
    name: "Sony WH-1000XM6",
    brand: "Sony",
    category: "Audio",
    subcategory: "Headphones",
    price: 34990,
    originalPrice: 39990,
    discount: 13,
    rating: 4.8,
    reviewCount: 18920,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=900&q=85",
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=900&q=85",
    ],
    badge: "Hot",
    inStock: true,
    emi: "₹1,166/mo",
    delivery: "Free delivery Tomorrow",
    warranty: "1 Year Sony Warranty",
    description: "Industry-leading noise cancellation. Wear them all day with 30-hour battery and class-leading sound quality.",
    highlights: ["Industry-leading ANC", "30-hour battery life", "Hi-Res Audio certified", "Speak-to-Chat technology", "Multipoint Bluetooth 5.3"],
    specs: [
      { label: "Driver", value: "40mm custom dynamic" },
      { label: "Frequency", value: "4Hz – 40,000Hz" },
      { label: "Battery", value: "30 hours (ANC on)" },
      { label: "Bluetooth", value: "5.3, multipoint" },
      { label: "Weight", value: "250g" },
      { label: "Folds", value: "Yes, for travel" },
    ],
    colors: ["#1a1a1a", "#f5f0e8", "#2563eb"],
    tags: ["anc", "wireless", "bestseller"],
  },
  {
    id: "p5",
    name: "Apple Watch Series 10",
    brand: "Apple",
    category: "Smartwatches",
    price: 46900,
    originalPrice: 49900,
    discount: 6,
    rating: 4.7,
    reviewCount: 7320,
    image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=900&q=85",
    ],
    badge: "New",
    inStock: true,
    emi: "₹1,563/mo",
    delivery: "Free delivery Tomorrow",
    warranty: "1 Year Apple Warranty",
    description: "The thinnest Apple Watch ever. Blood oxygen, ECG, advanced sleep tracking, and crash detection — all in a redesigned case.",
    highlights: ["Thinnest Apple Watch design", "ECG + Blood Oxygen app", "Advanced crash detection", "S10 SiP dual-core processor", "WR50 water resistance"],
    specs: [
      { label: "Display", value: "46mm LTPO OLED, 2000 nits" },
      { label: "Chip", value: "Apple S10 SiP" },
      { label: "Battery", value: "Up to 18 hours" },
      { label: "Water", value: "WR50, swim-proof" },
      { label: "Sensors", value: "ECG, Blood O₂, skin temperature" },
      { label: "Connectivity", value: "GPS + Cellular" },
    ],
    colors: ["#1a1a1a", "#c0c0c0", "#f5e6c8", "#dc143c"],
    tags: ["health", "fitness", "gps"],
  },
  {
    id: "p6",
    name: "Sony PlayStation 5 Pro",
    brand: "Sony",
    category: "Gaming",
    price: 66990,
    originalPrice: 71990,
    discount: 7,
    rating: 4.8,
    reviewCount: 4210,
    image: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=900&q=85",
    ],
    badge: "Hot",
    inStock: true,
    emi: "₹2,233/mo",
    delivery: "Free delivery in 2 days",
    warranty: "1 Year Sony Warranty",
    description: "PlayStation 5 Pro. 3× faster rendering with PSSR. 8K ready with 4K@120fps gaming and 2TB SSD.",
    highlights: ["PlayStation Spectral Super Resolution", "8K ready, 4K@120fps", "2TB ultra-fast SSD", "45 upgraded games at launch", "DualSense Edge compatible"],
    specs: [
      { label: "CPU", value: "AMD Zen 2, 8-core 3.85GHz" },
      { label: "GPU", value: "AMD RDNA 3.5, 33.5 TFLOPS" },
      { label: "Storage", value: "2TB NVMe SSD" },
      { label: "RAM", value: "16GB GDDR6" },
      { label: "Resolution", value: "Up to 8K" },
      { label: "Optical", value: "4K UHD Blu-ray" },
    ],
    tags: ["gaming", "console", "4k"],
  },
  {
    id: "p7",
    name: "Samsung 65\" Neo QLED 8K TV",
    brand: "Samsung",
    category: "Televisions",
    price: 249990,
    originalPrice: 299990,
    discount: 17,
    rating: 4.6,
    reviewCount: 2840,
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?w=900&q=85",
    ],
    badge: "Sale",
    inStock: true,
    emi: "₹8,333/mo",
    delivery: "Free delivery in 4 days",
    warranty: "2 Year Samsung Warranty",
    description: "See everything in extraordinary detail. Neo QLED 8K with Quantum Matrix Technology Pro and Neural Quantum Processor.",
    highlights: ["8K AI upscaling on every input", "Quantum Matrix Technology Pro", "Anti-reflection screen", "144Hz gaming mode", "Dolby Atmos & Object Tracking Sound"],
    specs: [
      { label: "Display", value: "65-inch Neo QLED 8K, 144Hz" },
      { label: "Resolution", value: "7680×4320 (8K)" },
      { label: "HDR", value: "Quantum HDR 64×" },
      { label: "Processor", value: "Neural Quantum Processor 8K" },
      { label: "Smart OS", value: "Tizen 8.0" },
      { label: "Ports", value: "4× HDMI 2.1, 3× USB" },
    ],
    tags: ["8k", "large-screen", "gaming"],
  },
  {
    id: "p8",
    name: "DJI Osmo Pocket 3",
    brand: "DJI",
    category: "Cameras",
    price: 44990,
    originalPrice: 49990,
    discount: 10,
    rating: 4.7,
    reviewCount: 3120,
    image: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=900&q=85",
    ],
    badge: "New",
    inStock: true,
    emi: "₹1,500/mo",
    delivery: "Free delivery in 2 days",
    warranty: "1 Year DJI Warranty",
    description: "Pocket-sized 3-axis gimbal camera with 1-inch CMOS sensor, 4K@120fps, and ActiveTrack 3.0 for silky smooth footage.",
    highlights: ["1-inch CMOS sensor", "4K@120fps video", "3-axis motorised gimbal", "ActiveTrack 3.0 subject tracking", "140-minute battery life"],
    specs: [
      { label: "Sensor", value: '1" CMOS, 9.33MP' },
      { label: "Video", value: "4K@120fps, 4K@60fps" },
      { label: "Stabilisation", value: "3-axis motorised gimbal" },
      { label: "Screen", value: "2-inch touchscreen" },
      { label: "Battery", value: "1,300 mAh, 140 min" },
      { label: "Weight", value: "179g" },
    ],
    tags: ["video", "compact", "gimbal"],
  },
  {
    id: "p9",
    name: "OnePlus 13 5G",
    brand: "OnePlus",
    category: "Smartphones",
    price: 69999,
    originalPrice: 79999,
    discount: 13,
    rating: 4.6,
    reviewCount: 6540,
    image: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=900&q=85",
    ],
    badge: "Trending",
    inStock: true,
    emi: "₹2,333/mo",
    delivery: "Free delivery Tomorrow",
    warranty: "1 Year OnePlus Warranty",
    description: "Snapdragon 8 Elite with Hasselblad camera tuning, 100W SUPERVOOC fast charging, and the signature alert slider.",
    highlights: ["Snapdragon 8 Elite processor", "Hasselblad-tuned triple camera", "100W SUPERVOOC charging", "Alert Slider for quick profiles", "5800 mAh battery"],
    specs: [
      { label: "Display", value: "6.82-inch LTPO AMOLED, 4500 nits, 120Hz" },
      { label: "Processor", value: "Snapdragon 8 Elite" },
      { label: "RAM", value: "16GB LPDDR5X" },
      { label: "Camera", value: "50MP + 50MP + 50MP" },
      { label: "Battery", value: "5800 mAh" },
      { label: "Charging", value: "100W SUPERVOOC" },
    ],
    colors: ["#0a0a0a", "#1a3a2a", "#8b4513"],
    storage: ["256GB", "512GB"],
    tags: ["5g", "fast-charge", "flagship"],
  },
  {
    id: "p10",
    name: "Dell XPS 15 OLED",
    brand: "Dell",
    category: "Laptops",
    price: 159990,
    originalPrice: 179990,
    discount: 11,
    rating: 4.5,
    reviewCount: 3840,
    image: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=900&q=85",
    ],
    badge: "Sale",
    inStock: true,
    emi: "₹5,333/mo",
    delivery: "Free delivery in 2 days",
    warranty: "1 Year Dell Warranty + 2 Year Extended",
    description: "Core Ultra 9 185H with Intel Arc GPU and a breathtaking 3.5K OLED 60Hz display. The creator's laptop refined.",
    highlights: ["Intel Core Ultra 9 185H", "3.5K OLED InfinityEdge display", "Dedicated NVIDIA RTX 4060", "86Wh battery, 130W USB-C charge", "Precision touchpad, backlit keyboard"],
    specs: [
      { label: "Display", value: "15.6-inch 3.5K OLED, 60Hz" },
      { label: "Processor", value: "Intel Core Ultra 9 185H" },
      { label: "RAM", value: "32GB DDR5" },
      { label: "GPU", value: "NVIDIA RTX 4060 8GB" },
      { label: "Storage", value: "1TB NVMe SSD" },
      { label: "Battery", value: "86Wh, up to 12 hours" },
    ],
    storage: ["512GB", "1TB", "2TB"],
    colors: ["#c0c0c0", "#1a1a1a"],
    tags: ["creator", "oled", "gaming"],
  },
  {
    id: "p11",
    name: "AirPods Pro 2nd Gen",
    brand: "Apple",
    category: "Audio",
    subcategory: "Earbuds",
    price: 24900,
    originalPrice: 26900,
    discount: 7,
    rating: 4.7,
    reviewCount: 21450,
    image: "https://images.unsplash.com/photo-1606220838315-056192d5e927?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1606220838315-056192d5e927?w=900&q=85",
    ],
    badge: "Trending",
    inStock: true,
    emi: "₹830/mo",
    delivery: "Free delivery Tomorrow",
    warranty: "1 Year Apple Warranty",
    description: "Adaptive Audio. Personalized Spatial Audio. Up to 30 hours total listening. The most capable AirPods ever.",
    highlights: ["Adaptive Transparency", "H2 chip with 2× ANC improvement", "Personalised Spatial Audio", "30 hours total battery", "Find My speaker in case"],
    specs: [
      { label: "Chip", value: "Apple H2" },
      { label: "ANC", value: "Up to 2× better than Gen 1" },
      { label: "Battery", value: "6hr + 24hr case = 30hr total" },
      { label: "Charging", value: "Lightning / MagSafe / USB-C" },
      { label: "Resistance", value: "IPX4" },
      { label: "Connectivity", value: "Bluetooth 5.3" },
    ],
    colors: ["#f5f5f5"],
    tags: ["anc", "wireless", "magsafe"],
  },
  {
    id: "p12",
    name: "Samsung Galaxy Watch 7",
    brand: "Samsung",
    category: "Smartwatches",
    price: 29999,
    originalPrice: 34999,
    discount: 14,
    rating: 4.5,
    reviewCount: 5620,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900&q=85",
    ],
    badge: "Sale",
    inStock: true,
    emi: "₹1,000/mo",
    delivery: "Free delivery Tomorrow",
    warranty: "1 Year Samsung Warranty",
    description: "Advanced health monitoring with BioActive Sensor 2.0. Body Composition analysis, sleep apnea detection, and AI energy score.",
    highlights: ["BioActive Sensor 2.0 — 3-in-1", "Sleep apnea detection (FDA cleared)", "Body composition analysis", "AI-powered energy score", "40-hour battery with sleep tracking"],
    specs: [
      { label: "Display", value: "47mm 1.5-inch Super AMOLED" },
      { label: "Chip", value: "Exynos W1000 5-core" },
      { label: "Sensors", value: "BioActive 2.0, SpO2, ECG, temp" },
      { label: "Battery", value: "425 mAh, up to 40 hours" },
      { label: "Water", value: "5ATM + IP68" },
      { label: "Connectivity", value: "LTE + GPS" },
    ],
    colors: ["#1a1a1a", "#c0c0c0", "#2563eb", "#16a34a"],
    tags: ["health", "fitness", "android"],
  },
  {
    id: "p13",
    name: "Dyson V15 Detect Absolute",
    brand: "Dyson",
    category: "Home Appliances",
    price: 59900,
    originalPrice: 74900,
    discount: 20,
    rating: 4.6,
    reviewCount: 3200,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=85",
    ],
    badge: "Sale",
    inStock: true,
    emi: "₹1,997/mo",
    delivery: "Free delivery in 3 days",
    warranty: "2 Year Dyson Warranty",
    description: "The most powerful cordless vacuum. HEPA filtration with piezo sensor that counts dust particles in real time.",
    highlights: ["262 AW suction power", "Piezo sensor counts particles", "Laser Slim Fluffy head", "HEPA filtration (whole-machine)", "Up to 60 minutes runtime"],
    specs: [
      { label: "Suction", value: "262 AW" },
      { label: "Runtime", value: "Up to 60 minutes" },
      { label: "Filtration", value: "HEPA whole-machine sealed" },
      { label: "Capacity", value: "0.76L" },
      { label: "Weight", value: "3.1 kg" },
      { label: "Bin", value: "Point and shoot ejection" },
    ],
    tags: ["cordless", "hepa", "smart"],
  },
  {
    id: "p14",
    name: "Google Nest Hub Max",
    brand: "Google",
    category: "Smart Home",
    price: 19999,
    originalPrice: 22999,
    discount: 13,
    rating: 4.4,
    reviewCount: 2140,
    image: "https://images.unsplash.com/photo-1558618047-3c8b8e1da2fe?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1558618047-3c8b8e1da2fe?w=900&q=85",
    ],
    badge: "Trending",
    inStock: true,
    emi: "₹667/mo",
    delivery: "Free delivery Tomorrow",
    warranty: "1 Year Google Warranty",
    description: "10-inch smart display powered by Google Assistant. Face Match, Nest camera, ambient EQ display, and Matter support.",
    highlights: ["10-inch HD touchscreen", "Built-in Nest camera with Face Match", "Full Google Assistant", "Ambient EQ auto-adjusts display", "Matter + Thread smart home hub"],
    specs: [
      { label: "Display", value: "10-inch 1280×800 IPS, ambient EQ" },
      { label: "Camera", value: "6.5MP 127° FOV" },
      { label: "Audio", value: "Speaker + 2 tweeters" },
      { label: "Smart Home", value: "Matter, Thread, Zigbee hub" },
      { label: "Power", value: "30W AC" },
      { label: "Dimensions", value: "251.3×172.9×67.3mm" },
    ],
    colors: ["#f5f5f5", "#1a1a1a"],
    tags: ["smart-home", "display", "google"],
  },
  {
    id: "p15",
    name: "Nothing Ear (2)",
    brand: "Nothing",
    category: "Audio",
    subcategory: "Earbuds",
    price: 9999,
    originalPrice: 11999,
    discount: 17,
    rating: 4.4,
    reviewCount: 8720,
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=900&q=85",
    ],
    badge: "Trending",
    inStock: true,
    emi: "₹333/mo",
    delivery: "Free delivery Tomorrow",
    warranty: "1 Year Nothing Warranty",
    description: "True ANC with Adaptive mode. 11.6mm custom driver with LHDC 5.0 codec. The most honest-looking earbuds.",
    highlights: ["Triple-mic Active Noise Cancellation", "11.6mm custom driver", "LHDC 5.0 lossless audio", "36 hours total battery", "IP54 rated"],
    specs: [
      { label: "Driver", value: "11.6mm dynamic" },
      { label: "ANC", value: "Triple mic, adaptive" },
      { label: "Battery", value: "6hr + 30hr case = 36hr" },
      { label: "Codec", value: "LHDC 5.0, AAC, SBC" },
      { label: "Bluetooth", value: "5.3" },
      { label: "Weight", value: "4.5g per bud" },
    ],
    colors: ["#f5f5f5", "#1a1a1a"],
    tags: ["anc", "transparent-design", "value"],
  },
  {
    id: "p16",
    name: "GoPro HERO 13 Black",
    brand: "GoPro",
    category: "Cameras",
    price: 42500,
    originalPrice: 47500,
    discount: 11,
    rating: 4.6,
    reviewCount: 4320,
    image: "https://images.unsplash.com/photo-1487956382158-bb926046304a?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1487956382158-bb926046304a?w=900&q=85",
    ],
    badge: "New",
    inStock: true,
    emi: "₹1,417/mo",
    delivery: "Free delivery in 2 days",
    warranty: "1 Year GoPro Warranty",
    description: "5.3K60 video. 27MP photos. ND filter kit. HyperSmooth 6.0. The best GoPro action camera ever.",
    highlights: ["5.3K60 + 4K120 video", "27MP photos", "HyperSmooth 6.0 stabilisation", "Enduro battery — longest runtime", "Magnetic Swivel clip in box"],
    specs: [
      { label: "Video", value: "5.3K@60fps, 4K@120fps" },
      { label: "Photo", value: "27MP RAW + JPEG" },
      { label: "Stabilisation", value: "HyperSmooth 6.0" },
      { label: "Water", value: "Waterproof to 10m" },
      { label: "Battery", value: "Enduro, 70 min @5.3K" },
      { label: "Screen", value: "2.27-inch rear + 1.4-inch front" },
    ],
    tags: ["action", "4k", "waterproof"],
  },
]

export const CATEGORIES: Category[] = [
  { id: "smartphones", name: "Smartphones", icon: "📱", image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400&q=80", count: 240, description: "Latest flagship and budget phones" },
  { id: "laptops", name: "Laptops", icon: "💻", image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&q=80", count: 185, description: "Ultrabooks, gaming, workstation" },
  { id: "audio", name: "Audio", icon: "🎧", image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80", count: 320, description: "Headphones, earbuds, speakers" },
  { id: "smartwatches", name: "Smartwatches", icon: "⌚", image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400&q=80", count: 98, description: "Fitness trackers and smart bands" },
  { id: "gaming", name: "Gaming", icon: "🎮", image: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400&q=80", count: 410, description: "Consoles, PCs, accessories" },
  { id: "cameras", name: "Cameras", icon: "📷", image: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&q=80", count: 156, description: "DSLR, mirrorless, action cams" },
  { id: "tvs", name: "Televisions", icon: "📺", image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?w=400&q=80", count: 89, description: "4K, 8K, OLED, QLED displays" },
  { id: "smarthome", name: "Smart Home", icon: "🏠", image: "https://images.unsplash.com/photo-1558618047-3c8b8e1da2fe?w=400&q=80", count: 203, description: "Speakers, displays, automation" },
  { id: "appliances", name: "Appliances", icon: "🌀", image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80", count: 176, description: "Vacuum, air purifiers, more" },
  { id: "tablets", name: "Tablets", icon: "📲", image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&q=80", count: 67, description: "iPad, Android, drawing tablets" },
  { id: "accessories", name: "Accessories", icon: "🔌", image: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400&q=80", count: 890, description: "Cables, cases, chargers, more" },
]

export const BRANDS: Brand[] = [
  { id: "apple", name: "Apple", logo: "🍎", tagline: "Think Different", count: 128 },
  { id: "samsung", name: "Samsung", logo: "🔷", tagline: "Do What You Can't", count: 214 },
  { id: "sony", name: "Sony", logo: "⚡", tagline: "Be Moved", count: 98 },
  { id: "dell", name: "Dell", logo: "💎", tagline: "The Power to Do More", count: 76 },
  { id: "oneplus", name: "OnePlus", logo: "🔴", tagline: "Never Settle", count: 52 },
  { id: "dyson", name: "Dyson", logo: "🌀", tagline: "Engineered Obsessively", count: 34 },
  { id: "nothing", name: "Nothing", logo: "⚪", tagline: "For the Brave", count: 18 },
  { id: "google", name: "Google", logo: "🟡", tagline: "Organise the World", count: 44 },
  { id: "dji", name: "DJI", logo: "✈️", tagline: "The Future of Possible", count: 29 },
  { id: "gopro", name: "GoPro", logo: "🎥", tagline: "Be a HERO", count: 22 },
]

export const DEALS = PRODUCTS.filter(p => p.discount && p.discount >= 10)
export const NEW_LAUNCHES = PRODUCTS.filter(p => p.badge === "New")
export const BESTSELLERS = PRODUCTS.filter(p => p.reviewCount > 5000)
export const TRENDING = PRODUCTS.filter(p => p.badge === "Trending")
