export type Product = {
  id: string
  name: string
  category: string
  collection: string
  metal: string
  stone?: string
  price: number
  originalPrice?: number
  weight: string
  purity?: string
  image: string
  images: string[]
  badge?: "New" | "Bestseller" | "Limited" | "Bridal"
  certified: boolean
  description: string
  highlights: string[]
  details: { label: string; value: string }[]
  sizes?: string[]
}

export type Collection = {
  id: string
  name: string
  tagline: string
  image: string
  count: number
  theme: string
}

export type StoreLocation = {
  id: string
  city: string
  address: string
  area: string
  phone: string
  hours: string
  image: string
}

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Royal Kundan Bridal Set",
    category: "Bridal",
    collection: "Royal Bridal",
    metal: "22K Gold",
    stone: "Kundan, Ruby, Emerald",
    price: 1_85_000,
    weight: "142g",
    purity: "22K BIS Hallmarked",
    image: "https://images.unsplash.com/photo-1583292438338-39e574a78eba?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1583292438338-39e574a78eba?w=900&q=85",
      "https://images.unsplash.com/photo-1606800052052-a08af7148866?w=900&q=85",
    ],
    badge: "Bridal",
    certified: true,
    description: "A masterpiece of traditional artisanship, this Kundan bridal necklace set is meticulously crafted by our master artisans over 40 hours. Each stone is hand-set in the ancient Kundan tradition, creating a luminous mosaic of colour and light.",
    highlights: ["Hand-set Kundan technique", "Premium natural Ruby and Emerald", "22K BIS Hallmarked gold", "Includes matching earrings and maang tikka", "Lifetime exchange guarantee"],
    details: [
      { label: "Metal", value: "22K Yellow Gold" },
      { label: "Purity", value: "916 Hallmarked" },
      { label: "Weight", value: "142g (approx.)" },
      { label: "Stone", value: "Natural Kundan, Ruby, Emerald" },
      { label: "Setting", value: "Traditional Kundan" },
      { label: "Origin", value: "Rajasthan, India" },
    ],
  },
  {
    id: "2",
    name: "Solitaire Diamond Ring",
    category: "Diamond",
    collection: "Diamond Dreams",
    metal: "18K White Gold",
    stone: "Diamond",
    price: 2_20_000,
    weight: "4.2g",
    purity: "18K Hallmarked",
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=900&q=85",
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=900&q=85",
    ],
    badge: "Bestseller",
    certified: true,
    description: "A celebration of light and brilliance. This 1.2 carat round brilliant diamond is GIA certified, set in a classic four-prong 18K white gold setting that lets the stone breathe and sparkle from every angle.",
    highlights: ["1.2 carat GIA certified diamond", "VS1 clarity, G colour", "18K white gold prong setting", "GIA certificate included", "Complimentary engraving"],
    details: [
      { label: "Metal", value: "18K White Gold" },
      { label: "Diamond Weight", value: "1.20 Carats" },
      { label: "Cut", value: "Round Brilliant" },
      { label: "Clarity", value: "VS1" },
      { label: "Colour", value: "G" },
      { label: "Certification", value: "GIA Certified" },
      { label: "Ring Weight", value: "4.2g" },
    ],
    sizes: ["6", "7", "8", "9", "10", "11", "12"],
  },
  {
    id: "3",
    name: "Colombian Emerald Pendant",
    category: "Gemstone",
    collection: "Gemstone Garden",
    metal: "18K Yellow Gold",
    stone: "Colombian Emerald",
    price: 85_000,
    weight: "6.8g",
    image: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=900&q=85",
    ],
    badge: "New",
    certified: true,
    description: "The deep velvet green of a Colombian emerald, cradled in a hand-engraved 18K gold setting. This piece carries the essence of centuries-old craftsmanship and the rare beauty of one of the world's most precious gemstones.",
    highlights: ["Natural Colombian emerald — 2.8 carats", "Hand-engraved gold setting", "GRS certificate included", "18K BIS Hallmarked gold", "Includes 18-inch gold chain"],
    details: [
      { label: "Metal", value: "18K Yellow Gold" },
      { label: "Stone", value: "Natural Colombian Emerald" },
      { label: "Carat", value: "2.8 ct" },
      { label: "Origin", value: "Colombia" },
      { label: "Certification", value: "GRS Certified" },
      { label: "Weight", value: "6.8g" },
    ],
  },
  {
    id: "4",
    name: "Rose Gold Diamond Bangle",
    category: "Gold",
    collection: "Eternal Gold",
    metal: "18K Rose Gold",
    stone: "Diamond",
    price: 95_000,
    originalPrice: 1_15_000,
    weight: "22g",
    purity: "18K Hallmarked",
    image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=900&q=85",
    ],
    badge: "Bestseller",
    certified: true,
    description: "A modern heirloom. This rose gold bangle features a continuous pavé of brilliant-cut diamonds that catches light from every angle. The warm blush of rose gold creates a romantic contrast against the icy brilliance of the diamonds.",
    highlights: ["0.75 carat total diamond weight", "Pavé diamond setting", "18K rose gold", "Fits up to 2.5 inch wrist", "Hallmark certified"],
    details: [
      { label: "Metal", value: "18K Rose Gold" },
      { label: "Diamond", value: "0.75 ct total" },
      { label: "Setting", value: "Pavé" },
      { label: "Weight", value: "22g" },
      { label: "Diameter", value: "2.5 inches" },
    ],
  },
  {
    id: "5",
    name: "South Sea Pearl Necklace",
    category: "Fine Jewellery",
    collection: "Heritage Collection",
    metal: "18K White Gold",
    stone: "South Sea Pearl",
    price: 1_10_000,
    weight: "48g",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=900&q=85",
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=900&q=85",
    ],
    certified: true,
    description: "37 hand-selected South Sea pearls, each 12–14mm, strung on a silk thread with an 18K white gold clasp. The pearls are matched for their warm cream lustre and perfectly graduated for a silhouette that drapes beautifully.",
    highlights: ["37 matched South Sea pearls", "12–14mm pearl size", "18K white gold clasp", "Hand-knotted silk thread", "Comes in heritage jewellery box"],
    details: [
      { label: "Pearl", value: "South Sea (Australia)" },
      { label: "Size", value: "12–14mm" },
      { label: "Count", value: "37 pearls" },
      { label: "Clasp", value: "18K White Gold" },
      { label: "Length", value: "18 inches" },
    ],
  },
  {
    id: "6",
    name: "Burmese Ruby Cocktail Ring",
    category: "Gemstone",
    collection: "Gemstone Garden",
    metal: "18K Yellow Gold",
    stone: "Burmese Ruby",
    price: 3_25_000,
    weight: "8.4g",
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=900&q=85",
    ],
    badge: "Limited",
    certified: true,
    description: "Pigeon-blood Burmese ruby — the most prized colour in the world's most precious stone. This 3.8 carat oval ruby is surrounded by a halo of F-colour round brilliant diamonds set in 18K yellow gold. AGL certified.",
    highlights: ["3.8 ct pigeon-blood Burmese ruby", "0.62 ct diamond halo", "AGL certified ruby", "18K yellow gold", "Collector's piece — one of a kind"],
    details: [
      { label: "Ruby", value: "3.80 ct Burmese, Oval" },
      { label: "Colour", value: "Pigeon Blood" },
      { label: "Diamond", value: "0.62 ct, F/VS" },
      { label: "Metal", value: "18K Yellow Gold" },
      { label: "Certification", value: "AGL Certified" },
      { label: "Weight", value: "8.4g" },
    ],
    sizes: ["6", "7", "8", "9", "10"],
  },
  {
    id: "7",
    name: "Diamond Tennis Bracelet",
    category: "Diamond",
    collection: "Diamond Dreams",
    metal: "18K White Gold",
    stone: "Diamond",
    price: 4_50_000,
    weight: "14g",
    image: "https://images.unsplash.com/photo-1573408301185-9519f94874c3?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1573408301185-9519f94874c3?w=900&q=85",
    ],
    badge: "Bestseller",
    certified: true,
    description: "A river of diamonds. 52 perfectly matched round brilliant diamonds — 5.20 carats total — set in an elegant four-prong 18K white gold setting. The ultimate symbol of refined luxury.",
    highlights: ["5.20 carats total diamond weight", "52 perfectly matched diamonds", "F-G colour, VS clarity", "18K white gold four-prong setting", "Individual GIA certificates"],
    details: [
      { label: "Diamond", value: "5.20 ct total, 52 stones" },
      { label: "Cut", value: "Round Brilliant" },
      { label: "Colour", value: "F–G" },
      { label: "Clarity", value: "VS1–VS2" },
      { label: "Metal", value: "18K White Gold" },
      { label: "Length", value: "7 inches" },
      { label: "Certification", value: "GIA" },
    ],
  },
  {
    id: "8",
    name: "Antique Polki Choker",
    category: "Bridal",
    collection: "Royal Bridal",
    metal: "22K Gold",
    stone: "Polki Diamond, Emerald",
    price: 2_40_000,
    weight: "88g",
    purity: "22K BIS Hallmarked",
    image: "https://images.unsplash.com/photo-1606800052052-a08af7148866?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1606800052052-a08af7148866?w=900&q=85",
      "https://images.unsplash.com/photo-1583292438338-39e574a78eba?w=900&q=85",
    ],
    badge: "Bridal",
    certified: true,
    description: "This Mughal-inspired Polki choker is a labour of love — 120 hours of hand-crafting by our master karigar. Each uncut Polki diamond is hand-selected and set in the traditional foil-backed technique that has defined Indian royal jewellery for centuries.",
    highlights: ["Uncut Polki diamonds", "Traditional foil-back setting", "22K gold", "120 hours of craftsmanship", "Museum-quality packaging"],
    details: [
      { label: "Metal", value: "22K Yellow Gold" },
      { label: "Stone", value: "Uncut Polki, Natural Emerald" },
      { label: "Setting", value: "Traditional Foil-Back" },
      { label: "Weight", value: "88g" },
      { label: "Purity", value: "916 Hallmarked" },
      { label: "Craft", value: "Mughal, Jaipur" },
    ],
  },
  {
    id: "9",
    name: "Sapphire Stud Earrings",
    category: "Gemstone",
    collection: "Gemstone Garden",
    metal: "18K White Gold",
    stone: "Ceylon Sapphire",
    price: 68_000,
    weight: "3.2g",
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=900&q=85",
    ],
    badge: "New",
    certified: true,
    description: "A matched pair of cornflower-blue Ceylon sapphires, each 1.5 carats, set in a delicate bezel of 18K white gold with diamond-set surrounds. The colour is extraordinary — the saturated royal blue that Ceylon is celebrated for.",
    highlights: ["3.0 ct total Ceylon sapphires", "Matched pair — cornflower blue", "Diamond-set bezel surround", "GRS certified sapphires", "18K white gold"],
    details: [
      { label: "Sapphire", value: "3.0 ct total (1.5 ct each)" },
      { label: "Origin", value: "Ceylon (Sri Lanka)" },
      { label: "Colour", value: "Cornflower Blue" },
      { label: "Metal", value: "18K White Gold" },
      { label: "Certification", value: "GRS Certified" },
    ],
  },
  {
    id: "10",
    name: "22K Gold Temple Bangles Set",
    category: "Gold",
    collection: "Heritage Collection",
    metal: "22K Gold",
    price: 1_25_000,
    weight: "94g",
    purity: "22K BIS Hallmarked",
    image: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=900&q=85",
    ],
    certified: true,
    description: "A set of six temple-motif bangles in 22K gold, crafted using the lost-wax casting technique. Each bangle features intricate deity carvings derived from ancient temple architecture, a cherished heritage jewellery tradition of South India.",
    highlights: ["Set of 6 temple bangles", "Lost-wax casting technique", "Deity motif carvings", "22K BIS Hallmarked", "Available in sizes 2.4, 2.6, 2.8"],
    details: [
      { label: "Metal", value: "22K Yellow Gold" },
      { label: "Purity", value: "916 Hallmarked" },
      { label: "Weight", value: "94g (set of 6)" },
      { label: "Technique", value: "Lost-wax casting" },
      { label: "Style", value: "Temple jewellery" },
    ],
    sizes: ["2.4", "2.6", "2.8"],
  },
  {
    id: "11",
    name: "Diamond Halo Engagement Ring",
    category: "Diamond",
    collection: "Diamond Dreams",
    metal: "Platinum",
    stone: "Diamond",
    price: 3_75_000,
    weight: "5.8g",
    image: "https://images.unsplash.com/photo-1551122087-f999a9cd4eb7?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1551122087-f999a9cd4eb7?w=900&q=85",
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=900&q=85",
    ],
    badge: "Bestseller",
    certified: true,
    description: "A 1.5 carat oval-cut diamond at the centre, encircled by a single halo of 32 brilliant-cut diamonds, all set in PT950 platinum. This ring represents the pinnacle of engagement ring design — timeless, brilliant, and enduring.",
    highlights: ["1.50 ct oval centre diamond", "GIA certified — D, VVS1", "32 diamond halo surround", "PT950 platinum setting", "Complimentary custom engraving"],
    details: [
      { label: "Centre Diamond", value: "1.50 ct Oval" },
      { label: "Colour / Clarity", value: "D / VVS1" },
      { label: "Halo", value: "32 × 0.015 ct diamonds" },
      { label: "Total Diamond", value: "~1.98 ct" },
      { label: "Metal", value: "PT950 Platinum" },
      { label: "Certification", value: "GIA" },
    ],
    sizes: ["6", "7", "8", "9", "10", "11", "12"],
  },
  {
    id: "12",
    name: "Sterling Silver Kada",
    category: "Silver",
    collection: "Modern Minimal",
    metal: "Sterling Silver",
    price: 8_500,
    weight: "38g",
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=900&q=85",
    ],
    badge: "New",
    certified: true,
    description: "A bold, architectural kada in oxidised sterling silver. The twisted rope motif speaks to strength and continuity. Handcrafted by tribal artisans, this piece is a bridge between ancient tradition and contemporary design.",
    highlights: ["925 sterling silver", "Oxidised finish", "Handcrafted by tribal artisans", "Adjustable opening", "Anti-tarnish coating"],
    details: [
      { label: "Metal", value: "925 Sterling Silver" },
      { label: "Finish", value: "Oxidised" },
      { label: "Weight", value: "38g" },
      { label: "Hallmark", value: "BIS 925" },
    ],
  },
  {
    id: "13",
    name: "Tanzanite Drop Earrings",
    category: "Gemstone",
    collection: "Gemstone Garden",
    metal: "18K Yellow Gold",
    stone: "Tanzanite",
    price: 72_000,
    weight: "5.4g",
    image: "https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?w=900&q=85",
    ],
    badge: "Limited",
    certified: true,
    description: "Tanzanite — found only at the foothills of Mount Kilimanjaro, rarer than diamonds and growing more precious by the year. These 4.4 carat violet-blue tanzanite drops are set in brushed 18K gold for a contemporary elegance.",
    highlights: ["4.4 ct total tanzanite", "AAA grade — vivid violet-blue", "GIA certified", "18K brushed yellow gold", "Limited edition — 12 pairs worldwide"],
    details: [
      { label: "Stone", value: "Tanzanite" },
      { label: "Weight", value: "4.4 ct total" },
      { label: "Grade", value: "AAA — Vivid" },
      { label: "Origin", value: "Tanzania" },
      { label: "Metal", value: "18K Yellow Gold" },
    ],
  },
  {
    id: "14",
    name: "Gold Diamond Mangalsutra",
    category: "Gold",
    collection: "Eternal Gold",
    metal: "18K Gold",
    stone: "Diamond",
    price: 55_000,
    weight: "12g",
    purity: "18K Hallmarked",
    image: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=900&q=85",
    ],
    certified: true,
    description: "A contemporary interpretation of the sacred mangalsutra. The pendant features a brilliant-cut diamond-set motif in 18K gold, suspended from a black bead chain. Modern design, timeless meaning.",
    highlights: ["0.25 ct diamond pendant", "18K yellow gold", "Black bead chain", "18-inch adjustable length", "Comes with certificate of authenticity"],
    details: [
      { label: "Metal", value: "18K Yellow Gold" },
      { label: "Diamond", value: "0.25 ct" },
      { label: "Chain", value: "Black bead, 18 inch" },
      { label: "Weight", value: "12g" },
    ],
  },
  {
    id: "15",
    name: "Blue Sapphire Diamond Necklace",
    category: "Diamond",
    collection: "Diamond Dreams",
    metal: "18K White Gold",
    stone: "Kashmir Sapphire, Diamond",
    price: 8_50_000,
    weight: "18g",
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=900&q=85",
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=900&q=85",
    ],
    badge: "Limited",
    certified: true,
    description: "A Kashmir sapphire of extraordinary quality — 5.2 carats of the legendary velvety blue that connoisseurs seek above all others. Set as a pendant drop with 1.8 carats of surrounding diamonds in 18K white gold. GRS and GIA certified.",
    highlights: ["5.2 ct Kashmir sapphire — GRS certified", "Velvety blue Kashmir colour", "1.8 ct diamond surround", "GIA certified diamonds", "18K white gold, hand-fabricated"],
    details: [
      { label: "Sapphire", value: "5.20 ct Kashmir" },
      { label: "Colour", value: "Royal Blue — Velvety" },
      { label: "Certification", value: "GRS (sapphire), GIA (diamonds)" },
      { label: "Diamond", value: "1.80 ct, F/VS" },
      { label: "Metal", value: "18K White Gold" },
    ],
  },
  {
    id: "16",
    name: "22K Bridal Haar Necklace",
    category: "Bridal",
    collection: "Royal Bridal",
    metal: "22K Gold",
    price: 3_10_000,
    weight: "186g",
    purity: "22K BIS Hallmarked",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=85",
    images: [
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=900&q=85",
      "https://images.unsplash.com/photo-1583292438338-39e574a78eba?w=900&q=85",
    ],
    badge: "Bridal",
    certified: true,
    description: "The quintessential bridal haar — 186 grams of 22K gold in a graduating strand design with intricate nakshi work. This necklace has dressed brides across generations and carries the weight of celebration in every gram.",
    highlights: ["186g solid 22K gold", "Nakshi hand-engraving", "3-strand graduating design", "BIS 916 hallmarked", "Comes with authenticity certificate"],
    details: [
      { label: "Metal", value: "22K Yellow Gold" },
      { label: "Purity", value: "916 Hallmarked" },
      { label: "Weight", value: "186g" },
      { label: "Technique", value: "Nakshi engraving" },
      { label: "Length", value: "22 inches" },
    ],
  },
]

export const COLLECTIONS: Collection[] = [
  {
    id: "eternal-gold",
    name: "Eternal Gold",
    tagline: "The purest expression of a timeless metal.",
    image: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=800&q=85",
    count: 48,
    theme: "Gold",
  },
  {
    id: "diamond-dreams",
    name: "Diamond Dreams",
    tagline: "Light captured. Brilliance released.",
    image: "https://images.unsplash.com/photo-1551122087-f999a9cd4eb7?w=800&q=85",
    count: 36,
    theme: "Diamond",
  },
  {
    id: "royal-bridal",
    name: "Royal Bridal",
    tagline: "For the most important day. And every day after.",
    image: "https://images.unsplash.com/photo-1583292438338-39e574a78eba?w=800&q=85",
    count: 28,
    theme: "Bridal",
  },
  {
    id: "gemstone-garden",
    name: "Gemstone Garden",
    tagline: "The world's rarest colours, set forever.",
    image: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=800&q=85",
    count: 32,
    theme: "Gemstone",
  },
  {
    id: "heritage",
    name: "Heritage Collection",
    tagline: "Centuries of craftsmanship. A lifetime of beauty.",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=85",
    count: 22,
    theme: "Heritage",
  },
  {
    id: "modern-minimal",
    name: "Modern Minimal",
    tagline: "Less is the ultimate sophistication.",
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=85",
    count: 40,
    theme: "Contemporary",
  },
]

export const STORES: StoreLocation[] = [
  {
    id: "mumbai",
    city: "Mumbai",
    area: "Bandra West",
    address: "Shop 4, Linking Road, Bandra West, Mumbai 400050",
    phone: "+91 22 4000 0001",
    hours: "Mon–Sat: 10am–8pm  |  Sun: 11am–6pm",
    image: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&q=80",
  },
  {
    id: "delhi",
    city: "New Delhi",
    area: "Khan Market",
    address: "47 Khan Market, New Delhi 110003",
    phone: "+91 11 4000 0002",
    hours: "Mon–Sat: 10am–8pm  |  Sun: 11am–6pm",
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&q=80",
  },
  {
    id: "bangalore",
    city: "Bangalore",
    area: "UB City",
    address: "UB City Mall, Level 1, Vittal Mallya Road, Bangalore 560001",
    phone: "+91 80 4000 0003",
    hours: "Mon–Sun: 10am–9pm",
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&q=80",
  },
  {
    id: "chennai",
    city: "Chennai",
    area: "T. Nagar",
    address: "12 Usman Road, T. Nagar, Chennai 600017",
    phone: "+91 44 4000 0004",
    hours: "Mon–Sat: 9:30am–8:30pm  |  Sun: 10am–6pm",
    image: "https://images.unsplash.com/photo-1573408301185-9519f94874c3?w=600&q=80",
  },
  {
    id: "hyderabad",
    city: "Hyderabad",
    area: "Jubilee Hills",
    address: "Road No. 36, Jubilee Hills, Hyderabad 500033",
    phone: "+91 40 4000 0005",
    hours: "Mon–Sat: 10am–8pm  |  Sun: 11am–6pm",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
  },
]
